version: 0.2

phases:
  pre_build:
    commands:
      - dotnet restore WebApi/RevojiWebApi/RevojiWebApi.csproj
  build:
    commands:
      - ls
      - dotnet publish -c release -o ./build_output WebApi/RevojiWebApi/RevojiWebApi.csproj
artifacts:
  files:
    - ./build_output